language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install: 
  - sudo apt-get install -qq python-pip python-numpy python-scipy python-matplotlib
install: python setup.py develop
script: nosetests
